workflows:
  android-build:
    name: Android APK Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      java: 21
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Grant execute permission
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug -PversionName="0.1.0"
    artifacts:
      - app/build/outputs/apk/debug/*.apk
