workflows:
  android-build:
    name: Android APK Build
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      android:
        build_tools_version: "33.0.2"
        compile_sdk_version: 33
        target_sdk_version: 33
        ndk: r21d
      java: 21
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Grant execute permission
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
